export const SET_STUDENTS = "SET_STUDENTS"
export const ADD_STUDENT = "ADD_STUDENT"
export const EDIT_STUDENT = "EDIT_STUDENT"
export const DELETE_STUDENT = "DELETE_STUDENT"


export const SET_INTAKE = "SET_PEOPLE"
export const ADD_INTAKE = "ADD_INTAKE"
export const DELETE_INTAKE = "DELETE_INTAKE"
export const EDIT_INTAKE = "EDIT_INTAKE"

export const SET_STRATEGIES = "SET_STRATEGIES"
export const ADD_STRATEGY = "ADD_STRATEGY"
export const DELETE_STRATEGY = "DELETE_STRATEGY"
export const EDIT_STRATEGY = "EDIT_STRATEGY"

export const SET_FRAMEWORKS = "SET_FRAMEWORKS"
export const ADD_FRAMEWORK = "ADD_FRAMEWORK"
export const DELETE_FRAMEWORK = "DELETE_FRAMEWORK"
export const EDIT_FRAMEWORK = "EDIT_FRAMEWORK"

export const SET_TEAM= "SET_TEAM"
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER"
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER"
export const EDIT_TEAM_MEMBER = "EDIT_TEAM_MEMBER"