export const SET_STUDENTS = "SET_STUDENTS"
export const ADD_STUDENT = "ADD_STUDENT"
export const EDIT_STUDENT = "EDIT_STUDENT"
export const DELETE_STUDENT = "DELETE_STUDENT"


export const SET_STRATEGIES = "SET_STRATEGIES"
export const ADD_STRATEGY = "ADD_STRATEGY"
export const DELETE_STRATEGY = "DELETE_STRATEGY"
export const EDIT_STRATEGY = "EDIT_STRATEGY"

export const SET_CLASSROOMS = "SET_CLASSROOMS"
export const ADD_CLASSROOM = "ADD_CLASSROOM"
export const DELETE_CLASSROOM = "DELETE_CLASSROOM"
export const EDIT_CLASSROOM = "EDIT_CLASSROOM"

export const SET_NOTES = "SET_NOTES"
export const ADD_NOTE = "ADD_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const EDIT_NOTE = "EDIT_NOTE"

export const SET_COMMENTS = "SET_COMMENTS"
export const ADD_COMMENT = "ADD_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const EDIT_COMMENT = "EDIT_COMMENT"
